### ISSUE TITLE
想提4点建议

### ISSUE THREAD

**Issue by leoly886** [Hellager/Youbei#4]
想提4点建议。
1、请问能不能给程序加个定时备份功能， 每次开机不一样，想定到固定的时间备份。
2、最好在加个设置是否自动开机启动功能。
3、点叉关闭的时候能不能设置下，不要每次点叉要选择是最小化还是 关闭。 最好有个复选框。可以一直比如 是 最小化到任务栏；
4、最好设置好以后，启动就最小化到任务栏。不在桌面显示界面。

**Comment by Hellager** [comment]
1. 这个APSchedule里有自带的，可以改
2. 开机自启动其实可以自己加个bat，个人来说不是很喜欢开机自启动，可以考虑增加设置自己选择
3. 这个是想说关闭窗口可以默认模式? 然后最小化/退出程序的选项在别的设置里选择?
4. 这个确实没想到过，也考虑做个设置用户自己选
至于什么时候能改好，不能保证，我暂时有别的项目在忙

**Comment by Hellager** [comment]
已发布新版本添加上述功能
